name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    uses: Katsute/Workflows/.github/workflows/npm.electron.deploy.yml@main
    with:
      environment: Electron Make
      rebuild: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}