name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    uses: KatsuteDev/Workflows/.github/workflows/npm.deploy.electron.yml@main
    with:
      environment: Electron Make
    secrets: inherit